### ISSUE TITLE
Split titles into words

### ISSUE THREAD

**Issue by wbcbugfree** [soilwise-he/demo-zenodo-neo4j-llm-ilvo#1]
This demo runs perfectly fine, but I noticed that you use regular expressions to clean the texts when extracting DublinCore standardized metadata,
with this line, the title will be split into words: 
`title_element = [x.lower() for x in clean_normalize(element.text).split()] if element is not None else None`
And with this line, all stop words (the, is, ...) will be removed:
`title_element = [token for token in title_element if token not in stopwords]`.
Therefore, when converting above metadata to knowledge graph, each word from the original titles becomes a node, connected with their "SoilwiseDataSource" node by the relations "HAS_TITLE".
I'm curious what the purpose of doing this is. Because in subsequent querying, I have not observed any benefit from doing so. I also tried keeping the original title unchanged (without splitting it into words or removing stop words), and the results were essentially the same during querying.

**Comment by BerkvensNick** [comment]
@wbcbugfree , hi Beichen, thanks for the comment! and sorry for only replying now, I think I did not receive any notice on this issue or overlooked it. My logic for splitting the title into words and then removing the stopwords was a first quick attempt to also use the important words in the title as 'keywords' to use when searching for datafiles in the SWR (and there are extra NLP techniques to delete less important words if we chose this approach). Authors can provide some keywords when uploading a document, but this is sometimes limited. My quick attempt was to enrichen the search functionality by also adding the title words to the datafile-node. You probably use a query in which you define the serachword is part of/in the title? Did not think of this logic, but good to know it also works! Thanks for the input!
